apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-config
  labels:
    app: clinic-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-config
  template:
    metadata:
      labels:
        app: clinic-config
    spec:
      containers:
        - name: clinic-config
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/democonfig:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret