apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-config
  labels:
    app: clinic-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-config
  template:
    metadata:
      labels:
        app: clinic-config
    spec:
      containers:
        - name: clinic-config
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/clinic-config:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /bahmni_config  # Path where app expects configs
              subPath: bahmni_config     # Subpath from ConfigMap
      volumes:
        - name: config-volume
          configMap:
            name: clinic-config
      imagePullSecrets:
        - name: ecr-secret