apiVersion: v1
kind: Secret
metadata:
  name: reports-db-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQ=         # password
  db-name: YmFobW5pX3JlcG9ydHM=        # bahmni_reports
  db-user: cmVwb3J0cy11c2Vy           # reports-user
  db-password: cGFzc3dvcmQ=           # password
