apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-web
  labels:
    app: bahmni-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahmni-web
  template:
    metadata:
      labels:
        app: bahmni-web
    spec:
      containers:
        - name: bahmni-web
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/bahmni-web:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            # Mount the shared volume to Apache htdocs directory
            - name: shared-config-volume
              mountPath: /usr/local/apache2/htdocs/bahmni_config
      volumes:
        - name: shared-config-volume
          persistentVolumeClaim:
            claimName: bahmni-config-pvc
      imagePullSecrets:
        - name: ecr-secret