apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-web
  labels:
    app: bahmni-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahmni-web
  template:
    metadata:
      labels:
        app: bahmni-web
    spec:
      containers:
        - name: bahmni-web
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/bahmni-web:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/bahmni_config/openmrs/apps/home
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: bahmni-web-config
            items:
              - key: app.json
                path: app.json
              - key: extension.json
                path: extension.json
              - key: whiteLabel.json
                path: whiteLabel.json
              - key: offline-config.json
                path: offline-config.json
              - key: locale_languages.json
                path: locale_languages.json
      imagePullSecrets:
        - name: ecr-secret
