apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-web
  labels:
    app: bahmni-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahmni-web
  template:
    metadata:
      labels:
        app: bahmni-web
    spec:
      containers:
        - name: bahmni-web
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/bahmni-web:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/bahmni_config/openmrs/apps/home
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: bahmni-web-config
        - name: nginx-conf
          configMap:
            name: bahmni-nginx-conf
      imagePullSecrets:
        - name: ecr-secret
